TeadingPlatformMVC/TeadingPlatformMVC/Controllers/YcxCodeController.cs
using Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TeadingPlatformMVC.Models;

namespace TeadingPlatformMVC.Controllers
{
    public class YcxCodeController : Controller
    {
        HttpClientHelper clientHelper = new HttpClientHelper();
        #region Jia


        // GET: YcxCode
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserSelect()
        {

            return View();
        }
        [HttpPost]
        public void UserSelect(Ycx_User model, object data)
        {
            string url = "http://localhost:55041/ycx/add";  //api链接
            HttpClient client = new HttpClient();  //
            string str = JsonConvert.SerializeObject(model);
            HttpContent content = new StringContent(str);
            content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            HttpResponseMessage message = client.PostAsync(url, content).Result;
            string result = message.Content.ReadAsStringAsync().Result;
            int i = Convert.ToInt32(result);
            if (i > 0)
            {
                Response.Write("<script>alert('添加成功');</script>");
            }
            else
            {
                Response.Write("<script>alert('添加失败');</script>");
            }
        }


        public ActionResult SelectUser(object obj)
        {
            string url = "http://localhost:55041/ycx/PersonalInformation";
            HttpClient client = new HttpClient();

            HttpResponseMessage message = client.GetAsync(url).Result;
            string result = message.Content.ReadAsStringAsync().Result;
            List<Ycx_User> list = JsonConvert.DeserializeObject<List<Ycx_User>>(result);
            return View(list.ToList());
        }

        public ActionResult ExitUser()
        {
            return View();
        }
        [HttpPost]
        public void ExitUser(Ycx_User model, int id)
        {
            string url = "http://localhost:55041/ycx/exit?ids=" + id;
            HttpClient client = new HttpClient();
            string str = JsonConvert.SerializeObject(model);
            HttpContent content = new StringContent(str);
            content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            HttpResponseMessage message = client.PostAsync(url, content).Result;
            string result = message.Content.ReadAsStringAsync().Result;
            int key = Convert.ToInt32(result);
            if (key > 0)
            {
                Response.Write("<script>alert('修改成功');</script>");
            }
            else
            {
                Response.Write("<script>alert('修改失败')</script>");
            }
        }
        #endregion

        /// <summary>
        /// 添加一个信息
        /// </summary>
        /// <returns></returns>
        public ActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public void UserAdd(Ycx_User um)
        {
            try
            {
                var data = JsonConvert.SerializeObject(um);
                var request = Request["data"];
                UnitedReturn united = new UnitedReturn();
                var res = clientHelper.Post("api/User/Add", data);
                united = JsonConvert.DeserializeObject<UnitedReturn>(res.ToString());


                GetName name = new GetName();
                name.Name = united.msg;
                if (united.res > 0)
                {
                    Response.Write("<script>alert('添加成功');location.href='/YcxCode/ExUser'</script>");
                }
                else
                {
                    Response.Write("<script>alert('添加失败');</script>");
                }



            }
            catch (Exception)
            {

                throw;
            }

            //var data = Request["data"];
            //string url = "http://localhost:55041/ycx/Z_Add";
            //HttpClient client = new HttpClient();
            //string str = JsonConvert.SerializeObject(um);
            //HttpContent content = new StringContent(str);
            //content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            //HttpResponseMessage message = client.PostAsync(url, content).Result;
            //string result = message.Content.ReadAsStringAsync().Result;
            //GetName name = new GetName();
            //name.Name = result;
            //return Json(name, JsonRequestBehavior.AllowGet);

        }



        public ActionResult ExUser()
        {


            return View();
        }
        [HttpPost]
        public void ExUser(int id, Ycx_User um)
        {


            try
            {

                ////查看上传的文件
                //HttpFileCollectionBase files = Request.Files;
                //// true 有文件
                //// false  无文件

                //HttpPostedFileBase file = files["UserPhoto"];
                //string fullName = file.FileName;
                //FileInfo fi = new FileInfo(fullName);
                //string nameFile = fi.Name;
                //string uploadPath = Server.MapPath("\\UserPhoto");
                //file.SaveAs(uploadPath + "\\" + nameFile);

                long ids = Convert.ToInt64(id);
                var data = JsonConvert.SerializeObject(um);
               
                UnitedReturn united = new UnitedReturn();
                var res = clientHelper.Post($"api/User/UpdateUser?id="+ids, data);
                united = JsonConvert.DeserializeObject<UnitedReturn>(res.ToString());


                GetName name = new GetName();
                name.Name = united.msg;


                if (united.res > 0)
                {
                    Response.Write("<script>alert('修改成功');location.href='/YcxCode/Z_SelectUser'</script>");
                }
                else
                {
                    Response.Write("<script>alert('修改失败');</script>");
                }



            }
            catch (Exception)
            {

                throw;
            }
        }
        [HttpPost]
        public JsonResult EnUser()
        {
            var GetList = clientHelper.Post("api/User/SelectUser", 1);
            List<Ycx_User> GetData = new List<Ycx_User>();
            UnitedReturn united = new UnitedReturn();
            if (GetList != null)
            {
                united = JsonConvert.DeserializeObject<UnitedReturn>(GetList.ToString());
                GetData = JsonConvert.DeserializeObject<List<Ycx_User>>(JsonConvert.SerializeObject(united.data));
            }

            return Json(GetData.ToList());
        }

        public void UpLoad()
        {
            //查看上传的文件
            HttpFileCollectionBase files = Request.Files;
            // true 有文件
            // false  无文件

            HttpPostedFileBase file = files["img"];
            string fullName = file.FileName;
            FileInfo fi = new FileInfo(fullName);
            string nameFile = fi.Name;
            string uploadPath = Server.MapPath("\\UserPhoto");
            file.SaveAs(uploadPath + "\\" + nameFile);


        }


        public ActionResult Z_SelectUser()
        {
            var GetList = clientHelper.Post("api/User/SelectUser", 1);
            List<Ycx_User> GetData = new List<Ycx_User>();
            UnitedReturn united = new UnitedReturn();
            if (GetList != null)
            {
                united = JsonConvert.DeserializeObject<UnitedReturn>(GetList.ToString());
                GetData = JsonConvert.DeserializeObject<List<Ycx_User>>(JsonConvert.SerializeObject(united.data));
            }




            return View(GetData.ToList());
        }
        public ActionResult Z_SelectShop()
        {
            var GetList = clientHelper.Post("api/User/SelectType", 1);
            List<ShopInfo> shopSee = new List<ShopInfo>();
            UnitedReturn united = new UnitedReturn();
            if (GetList != null)
            {
                united = JsonConvert.DeserializeObject<UnitedReturn>(GetList.ToString());
                shopSee = JsonConvert.DeserializeObject<List<ShopInfo>>(JsonConvert.SerializeObject(united.data));
                List<Upload> items = new List<Upload>();
                items.Add(new Upload() { text = "请选择", value = "0", Selected = true });
                ViewData["DromDownlist"] = items;


            }
            return View(shopSee.ToList());
        }


    }

    public class Upload
    {
        public string text { get; set; }
        public string value { get; set; }
        public bool Selected { get; set; }
        public string uploadImage(FileUpload FUSShopURL, string UpladURL)
        {
            if (FUSShopURL.HasFile)
            {
                //获取当前时间，当作图片的名字
                string fileName = DateTime.Now.ToString("yyyyMMddhhmmss") + DateTime.Now.Millisecond.ToString();
                //获取图片的扩展名
                string Extent = System.IO.Path.GetExtension(FUSShopURL.PostedFile.FileName);
                //重命名图片
                fileName += Extent;
                //设置上传图片保存的文件夹
                string dir = System.Web.HttpContext.Current.Server.MapPath(UpladURL);
                //指定图片的路径及文件名
                string path = dir + "\\" + fileName;
                //把上传的图片保存到指定的文件中
                FUSShopURL.PostedFile.SaveAs(path);
                return fileName;
            }
            else
            {
                return "";
            }
        }
    }


}

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/AddUser.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/Scripts/layui/layui.css" rel="stylesheet" />
<link href="~/Scripts/layui/admin.css" rel="stylesheet" />

<div>
    @using (Html.BeginForm("UserAdd", "Ycxcode"))
    {



        <form class="layui-form">


            @*<div class="layui-tab-item layui-show">*@
            @*---------*@

            <div>
                <label class="layui-form-label">昵称：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserName" value="" class="layui-input" placeholder="请输入昵称" />
                </div>
            </div>


            @*<div class="layui-form-item">
                    <label class="layui-form-label">文章名称：</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" required lay-verify="required" placeholder="请输入文章名称" autocomplete="off" class="layui-input">
                    </div>
                </div>*@
            <div>
                <label class="layui-form-label">头像:</label>
                <div class="layui-input-block">
                    <input type="file" name="UserPhoto" value="" class="layui-upload-button" />

                </div>
            </div>
            

            <div class="layui-form-item">
                <label class="layui-form-label">性别：</label>
                <div class="layui-input-block">
                    <input type="radio" name="static" value="1" title="男" checked="">男
                    <input type="radio" name="static" value="0" title="女">女
                </div>
            </div>
            @*<div>
                    <label class="layui-form-label">性别：</label>
                    <div class="layui-input-block">
                        <input type="radio" name="sex" value="1" title="男"  />男

                        <input type="radio" name="sex" value="0" title="女"  />女

                    </div>
                </div>*@
        

            <div>
                <div>
                    <label class="layui-form-label">手机号：</label>
                    <div class="layui-input-block">
                        <input type="text" name="UserNumder" value="" class="layui-input" placeholder="请输入手机号码" />
                    </div>
                </div>


                <div>
                    <label class="layui-form-label">年龄：</label>
                    <div class="layui-input-block">
                        <input type="text" name="UserAge" value="" class="layui-input" placeholder="请输入年龄" />
                    </div>
                </div>

                <div>
                    <label class="layui-form-label">身份证：</label>
                    <div class="layui-input-block">
                        <input type="text" name="UserIDNumber" value="" class="layui-input" placeholder="请输入身份证" />
                    </div>
                </div>
                <div>

                    <div class="layui-input-block">
                        <input type="submit" name="UserName" value="添加" class="layui-input" placeholder="请输入昵称" />
                    </div>
                </div>
            </div>


            <div class="layui-form-item layui-form-text">
                @*
                    <label class="layui-form-label">文章内容：</label>
                    <div class="layui-input-block">
                        <textarea class="layui-textarea layui-hide" name="content" lay-verify="content" id="LAY_demo_editor"></textarea>
                    </div>
                *@
            </div>





            @*</div>*@



            @*<div class="layui-form-item" style="padding-left: 10px;">
                    <div class="layui-input-block">
                        <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>*@

        </form>

    }
    <script src="~/Scripts/layui.js"></script>


    <script type="text/javascript">
        var SCOPE = {
            static: '/static',
            index: '/admin/category/index.html',
            add: 'add.html',
            save: '/admin/category/save.html',
            edit: 'add.html',
            updateEdit: '/admin/category/updateedit.html',
            status: '/admin/category/updatestatus.html',
            del: '/admin/category/del.html',
            delAll: '/admin/category/deleteall.html',
            listOrderAll: '/admin/category/listorderall.html'
        }
    </script>

    <script src="~/Scripts/layui.js"></script>
    <script>

        layui.use(['form', 'jquery', 'laydate', 'layer', 'laypage', 'dialog', 'element', 'upload', 'layedit'], function () {
            var form = layui.form(),
                layer = layui.layer,
                $ = layui.jquery,
                laypage = layui.laypage,
                laydate = layui.laydate,
                layedit = layui.layedit,
                element = layui.element(),
                dialog = layui.dialog;

            //获取当前iframe的name值
            var iframeObj = $(window.frameElement).attr('name');
            //创建一个编辑器
            var editIndex = layedit.build('LAY_demo_editor', {
                tool: ['strong' //加粗
                    , 'italic' //斜体
                    , 'underline' //下划线
                    , 'del' //删除线
                    , '|' //分割线
                    , 'left' //左对齐
                    , 'center' //居中对齐
                    , 'right' //右对齐
                    , 'link' //超链接
                    , 'unlink' //清除链接
                    , 'image' //插入图片
                ],
                height: 100
            })
            //全选
            form.on('checkbox(allChoose)', function (data) {
                var child = $(data.elem).parents('table').find('tbody input[type="checkbox"]');
                child.each(function (index, item) {
                    item.checked = data.elem.checked;
                });
                form.render('checkbox');
            });
            form.render();

            layui.upload({
                url: '上传接口url',
                success: function (res) {
                    console.log(res); //上传成功返回值，必须为json格式
                }
            });
        });
    </script>


</div>


@*@using (Html.BeginForm("UserAdd", "Ycxcode"))
    {
        <div>
            <div>
                用户昵称：
                <input type="text" name="UserName" value="" />
            </div>
            <div>
                用户头像：
                <input type="file" name="UserPhoto" value="" />
            </div>
            <div>
                用户性别：
                <input type="radio" name="Sex" value="1" /> 男
                <input type="radio" name="Sex" value="0" />女
            </div>
            <div>
                用户手机号：
                <input type="text" name="UserNumder" value="" />
            </div>
            <div>
                用户年龄：
                <input type="text" name="UserAge" value="" />
            </div>
            <div>
                用户身份证：
                <input type="text" name="UserIDNumber" value="" />
            </div>
            <div>
                <input type="submit" name="name" value="添加" onclick="GetAddReturnMsg()" />


            </div>

        </div>
    }*@
@*<script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function GetAddReturnMsg() {
            $.ajax({
                url: "/TcxCode/UserAdd",
                dataType: "json",
                type: "POST",
                data: {},
                success: function (res) {
                    $(res).each(function () {
                        alert(this.Name);
                    })
                }
            })
        }
    </script>*@

<script>


</script>

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/ExUser.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<form action="/YcxCode/UpLoad3" method="post" enctype="multipart/form-data">
        <input type="file" name="img" value="" />
        <input type="submit" name="name" value="submit" />
    </form>*@

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

@using (Html.BeginForm("ExUser", "YcxCode"))
{


    <form action="/YcxCode/ExUser" method="post" enctype="multipart/form-data">
        @*<div class="layui-tab-item layui-show">*@
        @*---------*@

        <div>
            <label class="layui-form-label">昵称：</label>
            <div class="layui-input-block">
                <input type="text" name="UserName" id="UName" value=""  class="layui-input" placeholder="请输入昵称" />
            </div>
        </div>


        @*<div class="layui-form-item">
                <label class="layui-form-label">文章名称：</label>
                <div class="layui-input-block">
                    <input type="text" name="name" required lay-verify="required" placeholder="请输入文章名称" autocomplete="off" class="layui-input">
                </div>
            </div>*@

        <div>
            <label class="layui-form-label">头像:</label>
            <div class="layui-input-block">
                <input type="file" name="UserPhoto" value="12" class="layui-upload-button" />
                @*<input type="submit" name="name" value="上传" class="layui-upload-button" />*@
            </div>


        </div>




        <div class="layui-form-item">
            <label class="layui-form-label">性别：</label>
            <div class="layui-input-block">
                <input type="radio" name="static" value="1" title="男" checked="">男
                <input type="radio" name="static" value="0" title="女">女
            </div>
        </div>
        @*<div>
                <label class="layui-form-label">性别：</label>
                <div class="layui-input-block">
                    <input type="radio" name="sex" value="1" title="男"  />男

                    <input type="radio" name="sex" value="0" title="女"  />女

                </div>
            </div>*@


        <div>
            <div>
                <label class="layui-form-label">手机号：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserNumder" value="" class="layui-input" placeholder="请输入手机号码" />
                </div>
            </div>


            <div>
                <label class="layui-form-label">年龄：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserAge" value="" class="layui-input" placeholder="请输入年龄" />
                </div>
            </div>

            <div>
                <label class="layui-form-label">身份证：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserIDNumber" value="" class="layui-input" placeholder="请输入身份证" />
                </div>
            </div>
            <div>

                <div class="layui-input-block">
                    <input type="submit" value="编辑" class="layui-input" placeholder="请输入昵称" />
                </div>
            </div>
        </div>








        @*</div>*@



        @*<div class="layui-form-item" style="padding-left: 10px;">
                <div class="layui-input-block">
                    <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formDemo">立即提交</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>*@




    </form>
}
<script>
    $(EnUser);
    function EnUser() {
        $.ajax({
            url: '/YcxCode/EnUser',
            type: 'post',
            data: {
                
            },
            dataType:'json',
            success: {
                function (data) {
                    $("#UName").val() = $(this.UserName);
            }
            },


        });
    }


</script>

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/ExitUser.cshtml
@{
    Layout = null;
}
<div>

    @using (Html.BeginForm())
    {
        <div>
            <div>
                用户昵称：
                <input type="text" name="UserName" value="" />
            </div>
            <div>
                用户头像：
                <input type="text" name="UserPhoto" value="" />
            </div>
            <div>
                用户性别：
                <input type="text" name="UserSex" value="" />
            </div>
            <div>
                用户手机号：
                <input type="text" name="UserNumder" value="" />
            </div>
            <div>
                用户年龄：
                <input type="text" name="UserAge" value="" />
            </div>
            <div>
                用户身份证：
                <input type="text" name="UserIDNumber" value="" />
            </div>
            <div>
                <input type="submit" name="name" value="确定" />


            </div>

        </div>
    }


</div>

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/SelectUser.cshtml
@{
    Layout = null;
}
@model IEnumerable<TeadingPlatformMVC.Models.Ycx_User>




    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <div>
        <table class="table">
            <tr>
                <td>
                    用户编号
                </td>
                <td>
                    用户昵称
                </td>
                <td>
                    用户头像
                </td>
                <td>
                    用户性别
                </td>

                <td>
                    用户手机号
                </td>
                <td>
                    用户年龄
                </td>
                <td>
                    用户身份证
                </td>
                <td>
                </td>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.UserId
                    </td>
                    <td>
                        @item.UserName
                    </td>
                    <td>
                        
                        @item.UserPhoto
                    </td>
                    <td>
                        @item.UserSex
                    </td>

                    <td>
                        @item.UserNumder
                    </td>
                    <td>
                        @item.UserAge
                    </td>
                    <td>
                        @item.UserIDNumber
                    </td>
                    <td>
                        @Html.ActionLink("编辑", "ExitUser", new { @id=item.UserId}) |
                        @Html.ActionLink("删除", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }

        </table>
    </div>

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/UserSelect.cshtml
@{
      Layout = null;
}

<h2>UserSelect</h2>

@using (Html.BeginForm())
{
<div>
    <div>
        用户昵称：
        <input type="text" name="UserName" value="" />
    </div>
    <div>
        用户头像：
        <input type="file" name="UserPhoto" value="" />
    </div>
    <div>
        用户性别：
       <input type="radio" name="Sex" value="1" /> 男
       <input type="radio" name="Sex" value="0" />女
    </div>
    <div>
        用户手机号：
        <input type="text" name="UserNumder" value="" />
    </div>
    <div>
        用户年龄：
        <input type="text" name="UserAge" value="" />
    </div>
    <div>
        用户身份证：
        <input type="text" name="UserIDNumber" value="" />
    </div>
    <div>
        <input type="submit" name="name" value="添加" />


    </div>

</div>
}

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/Z_SelectShop.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Z_SelectShop</title>
</head>
<body>
    
</body>
</html>

TeadingPlatformMVC/TeadingPlatformMVC/Views/YcxCode/Z_SelectUser.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<TeadingPlatformMVC.Models.Ycx_User>
<link href="~/Scripts/layui/layui.css" rel="stylesheet" />
<link href="~/Scripts/layui/admin.css" rel="stylesheet" />



@foreach (var item in Model)
{

    <div>
        <form class="layui-form">


            @*<div class="layui-tab-item layui-show">*@
            @*---------*@

            <div>
                <label class="layui-form-label">昵称：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserName" value="@Html.DisplayFor(Model=>item.UserName)" class="layui-input" placeholder="请输入昵称" />
                </div>
            </div>


            @*<div class="layui-form-item">
                    <label class="layui-form-label">文章名称：</label>
                    <div class="layui-input-block">
                        <input type="text" name="name" required lay-verify="required" placeholder="请输入文章名称" autocomplete="off" class="layui-input">
                    </div>
                </div>*@
            <div>
                <label class="layui-form-label">头像:</label>
                <div class="layui-input-block">
                    <img src="~/UserPhoto/@item.UserPhoto" style="width:120px;height:80px" />

                </div>
            </div>

            <div>
                <label class="layui-form-label">年龄：</label>
                <div class="layui-input-block">
                    <input type="text" name="UserAge" value="@item.UserAge" class="layui-input" placeholder="请输入年龄" />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">性别：</label>
                <div class="layui-input-block">
                    <input type="radio" name="static" value="1" title="男" checked="checked">
                    <input type="radio" name="static" value="0" title="女">
                </div>
            </div>
            @*<div>
                    <label class="layui-form-label">性别：</label>
                    <div class="layui-input-block">
                        <input type="radio" name="sex" value="1" title="男"  />男

                        <input type="radio" name="sex" value="0" title="女"  />女

                    </div>
                </div>*@


            <div>
                <div>
                    <label class="layui-form-label">手机号：</label>
                    <div class="layui-input-block">
                        <input type="text" name="UserNumder" value="@item.UserNumder" class="layui-input" placeholder="请输入手机号码" />
                    </div>
                </div>




                <div>
                    <label class="layui-form-label">身份证：</label>
                    <div class="layui-input-block">
                        <input type="text" name="UserIDNumber" value="@item.UserIDNumber" class="layui-input" placeholder="请输入身份证" />
                    </div>
                </div>
                @Html.ActionLink("编辑", "ExUser", "YcxCode", new { id = item.UserNumder }, new { })
                
            </div>








            @*</div>*@



            @*<div class="layui-form-item" style="padding-left: 10px;">
                    <div class="layui-input-block">
                        <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>*@

        </form>

    </div>
}
<div>

</div>